apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-mongo-depl
  namespace: web-shop-showcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-mongo
  template:
    metadata:
      labels:
        app: server-mongo
    spec:
      containers:
        - name: server-mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
            - name: MONGO_INITDB_DATABASE
              value: web-shop-showcase-domain
---
apiVersion: v1
kind: Service
metadata:
  name: server-mongo-srv
  namespace: web-shop-showcase
spec:
  selector:
    app: server-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: server-mongo-ext-port
  namespace: web-shop-showcase
spec:
  type: NodePort
  selector:
    app: server-mongo
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30003
